### ISSUE TITLE
Duplicate rows

### ISSUE THREAD

**Issue by coudykid** [byu-transpolab/nhts2017#1]
Created function:
build_activities <- function(trips) {
+   
+   # create list of events labeled arrive or depart
+   events <- trips %>%
+     # exlude all other trip attributes
+     dplyr::select(houseid, personid, strttime, endtime, whyfrom, whyto) %>%
+     # gather times
+     tidyr::gather(strtend, time, strttime, endtime) %>%
+     dplyr::group_by(houseid, personid) %>%
+     # there have been errors where a time stamp is wrongly labeled and
+     # wrongly arranged here...and again on line 57
+     dplyr::arrange(time, .by_group = TRUE) %>%
+     dplyr::mutate(
+       event = ifelse(strtend == "strttime", "depart", "arrive"),
+       activity = ifelse(event == "depart", whyfrom, whyto)
+     )
+   
+   
+   # create the first activity for each person with a start time at 4 AM
+   first_activity <- events %>%
+     # take the starting point of each person
+     dplyr::slice(1) %>%
+     # creates a starting time for each person at 4:00:00 am
+     dplyr::transmute(
+       activity = as.character(whyfrom),
+       time = lubridate::as_datetime("2017-10-10 4:00:00"),
+       event = "arrive"
+     )
+   
+   # create the last activity for each person with an end time of 4AM the next day
+   last_activity <- events %>%
+     dplyr::slice(n()) %>%
+     dplyr::transmute(
+       activity = as.character(whyto),
+       time = lubridate::as_datetime("2017-10-11 4:00:00"),
+       event = "depart"
+     )
+   
+   # combine events with first and last activity
+   # spread by either arrive or depart
+   events %>%
+     dplyr::full_join(first_activity) %>%
+     dplyr::full_join(last_activity) %>%
+     dplyr::arrange(time, .by_group = TRUE) %>%
+     dplyr::select(-whyfrom, -whyto, -strtend) %>%
+     dplyr::group_by(houseid, personid, event) %>%
+     dplyr::mutate(activity_number = as.integer(factor(time))) %>%
+     tidyr::spread(event, time) %>%
+     dplyr::arrange(arrive, .by_group = TRUE)
+  
Ran function:
> build_activities(nhts_trips)
Joining, by = c("houseid", "personid", "time", "event", "activity")
Joining, by = c("houseid", "personid", "time", "event", "activity")

Received error:
Error: Each row of output must be identified by a unique combination of keys.
Keys are shared for 4 rows:
* 291998, 291999
* 840390, 840391
8. stop(fallback) 
7. signal_abort(cnd) 
6. abort(glue("Each row of output must be identified by a unique combination of keys.", 
    "\nKeys are shared for {shared} rows:", "\n{rows}")) 
5.  spread.data.frame(., event, time) 
4. tidyr::spread(., event, time) 
3. dplyr::arrange(., arrive, .by_group = TRUE) 
2. events %>% dplyr::full_join(first_activity) %>% dplyr::full_join(last_activity) %>% 
    dplyr::arrange(time, .by_group = TRUE) %>% dplyr::select(-whyfrom, 
    -whyto, -strtend) %>% dplyr::group_by(houseid, personid, 
    event) %>% dplyr::mutate(activity_number = as.integer(factor(time))) %>%  ... 
1. build_activities(nhts_trips) 

Any idea why I'm getting these duplicate rows?

**Comment by coudykid** [comment]
name: Label issues
on:
issues:
types:
- reopened
- opened
jobs:
label_issues:
runs-on: ubuntu-latest
permissions:
issues: write
steps:
- name: Label issues
uses: andymckay/labeler@5c59dab
with:
add-labels: "bug"
repo-token: ${{ secrets.GITHUB_TOKEN }}

**Comment by gregmacfarlane** [comment]
Not sure; would you mind cleaning up your submission so I better see what's going on / copy paste into my own session?

**Comment by gregmacfarlane** [comment]
Closing for lack of response
